version: '3.8'
services:

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=value
      - POSTGRES_USER=abdallh
      - POSTGRES_PASSWORD=thepassword
    container_name: postgres_con
    
  app:
    build: .
    volumes:
      - .:/django
    ports: 
      - 8000:8000
    image: app:django
    container_name:  decsion_app_container
    command: gunicorn project_django_pyrogram_bot.wsgi:application -c gunicorn.conf.py
    depends_on:
      - db

  celery:
    restart: always
    build: 
      context: .
    command: celery -A project_django_pyrogram_bot worker -l INFO
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - redis
      - app
      - db